# Generated by Django 4.1.3 on 2022-12-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=122)),
                ('Message', models.CharField(max_length=122)),
            ],
        ),
    ]
